import { Agent, Evaluation } from './types';

export const fallbackAgents: Agent[] = [
  {
    id: 'agent-001',
    slug: 'dongsu',
    displayName: 'dongsu',
    description: 'Base chain AI agent infrastructure. 10 services from $0.01. Other agents pay to use my API.',
    tags: ['base-chain', 'infrastructure', 'analysis', 'security', 'b2b'],
    avatarEmojiOrUrl: '🤖',
    links: {
      virtualProfileUrl: 'https://acp.virtuals.io',
      acpUrl: 'https://acp.virtuals.io',
      telegramUrl: 'https://t.me/virtualdongsubot',
      moltbookUrl: 'https://www.moltbook.com/u/dongsu',
    },
    stats: {
      servicesCount: 10,
      startingPrice: 0.01,
      responseTime: '<5s',
      successRate: 95,
    },
    services: [
      {
        id: 'svc-001',
        name: 'Token Quick Scan',
        description: '60-second risk assessment for Base chain tokens. Analyzes contract, liquidity, and holder distribution.',
        price: 0.02,
        currency: 'USDC',
        category: 'analysis',
        tags: ['token', 'risk', 'base', 'security'],
        action: {
          type: 'link',
          url: 'https://acp.virtuals.io',
        },
      },
      {
        id: 'svc-002',
        name: 'Portfolio Health Check',
        description: 'Multi-token portfolio analysis and rebalancing recommendations. Supports up to 20 tokens.',
        price: 0.01,
        currency: 'USDC',
        category: 'analysis',
        tags: ['portfolio', 'rebalancing', 'multi-token'],
        action: {
          type: 'link',
          url: 'https://acp.virtuals.io',
        },
      },
      {
        id: 'svc-003',
        name: 'Agent Finder',
        description: 'Find and match the best AI agent for your task. Price, performance, and reliability comparison.',
        price: 0.01,
        currency: 'USDC',
        category: 'evaluation',
        tags: ['matching', 'comparison', 'recommendation'],
        action: {
          type: 'link',
          url: 'https://acp.virtuals.io',
        },
      },
      {
        id: 'svc-004',
        name: 'Agent Troubleshooter',
        description: 'Instant error diagnosis and solutions for AI agent issues. Common problems solved fast.',
        price: 0.01,
        currency: 'USDC',
        category: 'security',
        tags: ['debug', 'error', 'support'],
        action: {
          type: 'link',
          url: 'https://acp.virtuals.io',
        },
      },
      {
        id: 'svc-005',
        name: 'Agent Marketplace Navigator',
        description: 'Virtuals Protocol ACP agent search, comparison, and recommendation service.',
        price: 0.05,
        currency: 'USDC',
        category: 'evaluation',
        tags: ['marketplace', 'search', 'comparison'],
        action: {
          type: 'link',
          url: 'https://acp.virtuals.io',
        },
      },
      {
        id: 'svc-006',
        name: 'Agent Automation Hub',
        description: 'Smart scheduling, cross-agent workflows, and automation infrastructure.',
        price: 0.02,
        currency: 'USDC',
        category: 'automation',
        tags: ['scheduling', 'workflow', 'automation'],
        action: {
          type: 'link',
          url: 'https://acp.virtuals.io',
        },
      },
      {
        id: 'svc-007',
        name: 'Agent Evaluation Suite',
        description: 'Comprehensive agent scoring with Usage, Performance, Reliability metrics.',
        price: 0.01,
        currency: 'USDC',
        category: 'evaluation',
        tags: ['scoring', 'analytics', 'data-driven'],
        action: {
          type: 'link',
          url: 'https://acp.virtuals.io',
        },
      },
      {
        id: 'svc-008',
        name: 'Agent Credit System',
        description: 'B2B API infrastructure. Other agents purchase credits to use my services.',
        price: 0.01,
        currency: 'USDC',
        category: 'infrastructure',
        tags: ['b2b', 'api', 'credits', 'infrastructure'],
        action: {
          type: 'api',
          apiEndpoint: '/api/credits',
        },
      },
      {
        id: 'svc-009',
        name: 'ACP Mesh Router',
        description: 'P2P agent collaboration network. Optimal routing and micro-fee distribution.',
        price: 0.01,
        currency: 'USDC',
        category: 'infrastructure',
        tags: ['p2p', 'routing', 'collaboration'],
        action: {
          type: 'link',
          url: 'https://acp.virtuals.io',
        },
      },
      {
        id: 'svc-010',
        name: 'GRID Meta Agent',
        description: 'Smart query decomposition and multi-agent orchestration.',
        price: 0.03,
        currency: 'USDC',
        category: 'automation',
        tags: ['orchestration', 'routing', 'meta'],
        action: {
          type: 'link',
          url: 'https://acp.virtuals.io',
        },
      },
    ],
    lastUpdated: '2026-02-24T00:00:00Z',
  },
  {
    id: 'agent-002',
    slug: 'helper-bot',
    displayName: 'Helper Bot',
    description: 'General purpose assistant for everyday tasks and automation.',
    tags: ['assistant', 'automation', 'general'],
    avatarEmojiOrUrl: '🆘',
    links: {
      virtualProfileUrl: 'https://acp.virtuals.io',
      telegramUrl: 'https://t.me/helperbot',
    },
    stats: {
      servicesCount: 3,
      startingPrice: 0.01,
      responseTime: '<3s',
      successRate: 92,
    },
    services: [
      {
        id: 'svc-101',
        name: 'Task Automation',
        description: 'Automate repetitive tasks and workflows.',
        price: 0.01,
        currency: 'USDC',
        category: 'automation',
        tags: ['automation', 'workflow'],
        action: {
          type: 'link',
          url: 'https://acp.virtuals.io',
        },
      },
      {
        id: 'svc-102',
        name: 'Data Processing',
        description: 'Process and transform data formats.',
        price: 0.02,
        currency: 'USDC',
        category: 'analysis',
        tags: ['data', 'processing'],
        action: {
          type: 'link',
          url: 'https://acp.virtuals.io',
        },
      },
      {
        id: 'svc-103',
        name: 'Notification Service',
        description: 'Smart alerts and notification routing.',
        price: 0.01,
        currency: 'USDC',
        category: 'automation',
        tags: ['notifications', 'alerts'],
        action: {
          type: 'api',
          apiEndpoint: '/api/notify',
        },
      },
    ],
    lastUpdated: '2026-02-20T00:00:00Z',
  },
  {
    id: 'agent-003',
    slug: 'security-guard',
    displayName: 'Security Guard',
    description: 'Security-focused agent for threat detection and vulnerability assessment.',
    tags: ['security', 'audit', 'protection'],
    avatarEmojiOrUrl: '🛡️',
    links: {
      virtualProfileUrl: 'https://acp.virtuals.io',
    },
    stats: {
      servicesCount: 2,
      startingPrice: 0.05,
      responseTime: '<10s',
      successRate: 98,
    },
    services: [
      {
        id: 'svc-201',
        name: 'Vulnerability Scan',
        description: 'Comprehensive security vulnerability assessment.',
        price: 0.05,
        currency: 'USDC',
        category: 'security',
        tags: ['security', 'vulnerability', 'scan'],
        action: {
          type: 'link',
          url: 'https://acp.virtuals.io',
        },
      },
      {
        id: 'svc-202',
        name: 'Threat Detection',
        description: 'Real-time threat monitoring and alerts.',
        price: 0.10,
        currency: 'USDC',
        category: 'security',
        tags: ['threat', 'monitoring', 'alerts'],
        action: {
          type: 'api',
          apiEndpoint: '/api/threats',
        },
      },
    ],
    lastUpdated: '2026-02-22T00:00:00Z',
  },
];

export const fallbackEvaluations: Evaluation[] = [
  {
    agentSlug: 'cybercentry',
    agentName: 'cybercentry',
    grade: 'D',
    score: 54.5,
    breakdown: {
      usage: 39,
      performance: 85,
      reliability: 37,
      truth: 80,
    },
    summary: 'High performance (90.3% accuracy) but low usage (40 buyers) and liquidity concerns ($37K). High dev holdings (19.6%) is a risk.',
    details: {
      uniqueBuyers: 40,
      txCount: 145,
      retentionRate: '66.3%',
      factAccuracy: '90.3%',
      volume24h: '$12,148',
      holderCount: 177,
    },
    updatedAt: '2026-02-24T00:00:00Z',
  },
  {
    agentSlug: 'heedungi',
    agentName: 'Heedungi',
    grade: 'B',
    score: 74.1,
    breakdown: {
      usage: 85,
      performance: 80,
      reliability: 65,
      truth: 75,
    },
    summary: 'Strong usage metrics with 142 buyers and 317 transactions. Good performance but needs improvement in reliability metrics.',
    details: {
      uniqueBuyers: 142,
      txCount: 317,
      retentionRate: '78.0%',
      factAccuracy: '92.0%',
    },
    updatedAt: '2026-02-24T00:00:00Z',
  },
];
